version: '2'
services:
  #certbot:
  #  image: certbot/certbot
  #  container_name: certbot
  #  volumes: 
  #    - ./certbot/conf:/etc/letsencrypt
  #    - ./certbot/www:/var/www/certbot
  #  command: certonly --webroot -w /var/www/certbot --force-renewal --email federico@fri3nds.com -d app.fri3nds.com --agree-tos
  api:
    platform: linux/amd64
    build:
      context: ./
    ports:
      - 80:3000
      - 443:3000
    #volumes:
      #- ./nginx/app.fri3nds.com/:/etc/nginx/certs
      #- ./nginx/certs/:/etc/nginx/certs
      #- ./.env/nginx.conf:/etc/nginx/nginx.conf
      #- ./data/certbot/conf:/etc/letsencrypt
      #- ./data/certbot/www:/var/www/certbot
      #- ./httpd.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
  
  

#aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 377876467573.dkr.ecr.us-east-1.amazonaws.com
#docker build --platform=linux/amd64 -t gninx-reverse-proxy .
#docker tag gninx-reverse-proxy:latest 377876467573.dkr.ecr.us-east-1.amazonaws.com/gninx-reverse-proxy:latest
#docker push 377876467573.dkr.ecr.us-east-1.amazonaws.com/gninx-reverse-proxy:latest

#docker tag gnix-reverse-proxy_nginx_1:latest 377876467573.dkr.ecr.us-east-1.amazonaws.com/gnix-reverse-proxy_nginx_1:latest
#docker push 377876467573.dkr.ecr.us-east-1.amazonaws.com/gnix-reverse-proxy_nginx_1:latest
